image: python:3.10

stages:
  - test

unit-test:
  stage: test
  script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run test

lint-test:
  stage: test
  script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run lint